//! Σ.C extension: plan + execute every TPC-H spec query (Q1..Q22)
//! against the SF=1 Parquet under `examples/tpch/data/sf1/`. Reports
//! pass / plan-fail / execute-fail per query. No correctness check
//! against tpchgen's reference answers — the SF=1 row counts vary
//! per query and the sum/avg comparisons are floating-point with
//! ordering caveats; the smoke test in `tests/tpch_smoke.rs` covers
//! that for Q6. This audit's job is to surface SQL-surface gaps in
//! DataFusion 53.1 across the full 22 before we wire them into the
//! bench harness.
//!
//! Usage:
//!     cargo run --release -p ematix-flow-core --example tpch_22_audit
//!
//! Reads SQL from `examples/tpch/queries/q01.sql` .. `q22.sql`,
//! generated by `tpch_extract_queries.rs`.

use std::path::PathBuf;
use std::time::Instant;

use datafusion::prelude::SessionContext;
use futures_util::TryStreamExt;

#[derive(Debug)]
enum Outcome {
    Pass { rows: usize, elapsed_ms: u128 },
    PlanFail(String),
    ExecuteFail(String),
}

const TPCH_TABLES: &[&str] = &[
    "region", "nation", "supplier", "customer", "part", "partsupp", "orders", "lineitem",
];

#[tokio::main(flavor = "multi_thread")]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let workspace = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .ok_or("workspace root not found")?
        .to_path_buf();
    let data_dir = std::env::var("TPCH_DATA_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| workspace.join("examples/tpch/data/sf1"));
    let queries_dir = workspace.join("examples/tpch/queries");

    let ctx = SessionContext::new();
    for table in TPCH_TABLES {
        let path = data_dir.join(format!("{table}.parquet"));
        if !path.exists() {
            return Err(format!(
                "missing {}\nGenerate first:\n  cargo run --release -p ematix-flow-core \
                 --example tpch_generate -- --sf 1 --out {}",
                path.display(),
                data_dir.display()
            )
            .into());
        }
        ctx.register_parquet(*table, path.to_str().unwrap(), Default::default())
            .await?;
    }

    println!("=== Σ.C extension TPC-H 22-query audit ===");
    println!("    data: {}", data_dir.display());
    println!("    queries: {}", queries_dir.display());
    println!();

    let mut outcomes: Vec<(u8, Outcome)> = Vec::with_capacity(22);
    for n in 1..=22u8 {
        let path = queries_dir.join(format!("q{n:02}.sql"));
        let sql = std::fs::read_to_string(&path)?;
        let outcome = run_one(&ctx, &sql).await;
        let tag = match &outcome {
            Outcome::Pass { rows, elapsed_ms } => format!("PASS ({rows} rows, {elapsed_ms} ms)"),
            Outcome::PlanFail(e) => format!("PLAN_FAIL: {}", short(e)),
            Outcome::ExecuteFail(e) => format!("EXEC_FAIL: {}", short(e)),
        };
        println!("Q{n:<2}  {tag}");
        outcomes.push((n, outcome));
    }

    let pass = outcomes
        .iter()
        .filter(|(_, o)| matches!(o, Outcome::Pass { .. }))
        .count();
    let plan_fail = outcomes
        .iter()
        .filter(|(_, o)| matches!(o, Outcome::PlanFail(_)))
        .count();
    let exec_fail = outcomes
        .iter()
        .filter(|(_, o)| matches!(o, Outcome::ExecuteFail(_)))
        .count();
    println!();
    println!("=== summary ===");
    println!("    PASS:       {pass}/22");
    println!("    PLAN_FAIL:  {plan_fail}");
    println!("    EXEC_FAIL:  {exec_fail}");

    if pass < 22 {
        std::process::exit(1);
    }
    Ok(())
}

async fn run_one(ctx: &SessionContext, sql: &str) -> Outcome {
    let start = Instant::now();
    let df = match ctx.sql(sql).await {
        Ok(df) => df,
        Err(e) => return Outcome::PlanFail(format!("{e}")),
    };
    let stream = match df.execute_stream().await {
        Ok(s) => s,
        Err(e) => return Outcome::ExecuteFail(format!("execute_stream: {e}")),
    };
    let batches: Result<Vec<_>, _> = stream.try_collect().await;
    let elapsed_ms = start.elapsed().as_millis();
    match batches {
        Ok(b) => {
            let rows: usize = b.iter().map(|rb| rb.num_rows()).sum();
            Outcome::Pass { rows, elapsed_ms }
        }
        Err(e) => Outcome::ExecuteFail(format!("collect: {e}")),
    }
}

fn short(msg: &str) -> String {
    msg.lines()
        .next()
        .unwrap_or(msg)
        .chars()
        .take(140)
        .collect()
}
