"""``flow init <path>`` — scaffold a new ematix-flow project.

Maven-archetype-style: drops a small, working pipeline + connection
config + Docker + systemd unit into the given directory so a new
user can `flow run` immediately. Lowers time-to-first-pipeline.

The scaffold deliberately includes only files that need to exist
before the first run; users add their own structure on top. No
opinionated package layout, no preconfigured CI — just enough to be
runnable.
"""
from __future__ import annotations

from pathlib import Path

__all__ = ["scaffold_project"]


_PIPELINES_PY = '''\
"""Example pipeline — runs every hour, copies from source to target.

`flow run example_sync --module pipelines` runs once.
`flow run-due --module pipelines --interval 60` runs all-due once.
`flow scheduler --module pipelines` runs the long-running scheduler.
"""
from __future__ import annotations

from ematix_flow import ematix, pipeline


@pipeline.register(name="example_sync", schedule="0 * * * *")
def example_sync() -> dict:
    """Stub pipeline body — replace with your real sync."""
    # This is where you'd call ematix.pipeline / ematix.warehouse_pipeline
    # / ematix.streaming_pipeline. The simplest possible body just
    # returns a dict describing the work.
    return {"rows_synced": 0, "note": "edit pipelines.py to add real work"}


# More examples (uncomment + adapt):
#
# @ematix.pipeline(
#     target=YourTargetTable,
#     source_table="public.your_source",
#     mode="merge",
#     schedule="*/15 * * * *",
# )
# def my_table_sync(src, tgt):
#     return "SELECT id, name, updated_at FROM public.your_source"
#
# @ematix.warehouse_pipeline(
#     source=WarehouseSource(connection=snowflake_prod,
#                            sql="SELECT * FROM events", kind="snowflake"),
#     target=WarehouseTarget.bigquery_table(bq_prod, "events_copy"),
#     schedule="@daily",
# )
# def daily_event_copy():
#     return None
'''


_CONNECTIONS_TOML = '''\
# ematix-flow connection registry.
#
# Each [[connection]] block defines a typed handle a pipeline can
# reference by name. Credentials use ${VAR} interpolation against env
# vars; ${vault:path#key} / ${aws:secret#field} / ${gcp:secret#version}
# route to registered secret resolvers (see USER_GUIDE.md).

# [[connection]]
# name = "warehouse"
# kind = "postgres"
# url = "postgres://app:${WAREHOUSE_PASSWORD}@db.example.com:5432/main"

# [[connection]]
# name = "kafka_prod"
# kind = "kafka"
# bootstrap_servers = "${KAFKA_BOOTSTRAP}"
# group_id = "ematix-flow"
'''


_DOCKERFILE = '''\
# Container for running ematix-flow pipelines.
#
# Build:  docker build -t my-flow:latest .
# Run:    docker run --rm \\
#           --env-file .env \\
#           my-flow:latest \\
#           flow scheduler --module pipelines --interval 30
FROM python:3.12-slim

RUN apt-get update \\
    && apt-get install -y --no-install-recommends ca-certificates curl \\
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Pin ematix-flow + the extras your pipelines actually need.
# Examples:
#   pip install "ematix-flow[postgres,kafka,observability]"
#   pip install "ematix-flow[warehouses]"
RUN pip install --no-cache-dir "ematix-flow>=0.5.0"

COPY pipelines.py ./
COPY connections.toml ./

# Default CMD runs the scheduler; override to `flow doctor` / `flow run`
# / `flow run-due` as needed.
CMD ["flow", "scheduler", "--module", "pipelines", "--interval", "30"]
'''


_FLOW_SERVICE = '''\
[Unit]
Description=ematix-flow scheduler
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=ematix-flow
WorkingDirectory=/opt/ematix-flow
EnvironmentFile=-/etc/ematix-flow/env
# Replace --module / --interval to match your project layout.
ExecStart=/usr/local/bin/flow scheduler --module pipelines --interval 30
Restart=on-failure
RestartSec=5s
# Sane resource defaults; tune per your workload.
LimitNOFILE=65536
ProtectSystem=strict
ProtectHome=true
NoNewPrivileges=true
ReadWritePaths=/var/lib/ematix-flow

[Install]
WantedBy=multi-user.target
'''


_GITIGNORE = '''\
__pycache__/
*.pyc
.env
.venv/
*.log
'''


_README = '''\
# ematix-flow project

Scaffold generated by `flow init`.

## Start

```sh
# Install ematix-flow with the extras your pipelines use.
pip install "ematix-flow[postgres,observability]"

# Run a single pipeline.
flow run example_sync --module pipelines

# Run every pipeline that's due in the last 60 seconds.
flow run-due --module pipelines --interval 60

# Long-running scheduler.
flow scheduler --module pipelines --interval 30
```

## Layout

* `pipelines.py`     — declare your @pipeline.register / @ematix.pipeline /
  @ematix.warehouse_pipeline / @ematix.streaming_pipeline functions
* `connections.toml` — named DB / Kafka / S3 / warehouse connections
* `Dockerfile`       — container image for production
* `flow.service`     — systemd unit (drop into /etc/systemd/system/)

## Pre-deploy check

```sh
flow doctor --module pipelines
```

Probes every registered connection and reports green/red. Use as a
gate in CI before promoting to prod.

## Docs

* USER_GUIDE.md (in the ematix-flow repo)
* DEPLOYMENT.md (in the ematix-flow repo)
'''


def scaffold_project(target_dir: Path, *, force: bool = False) -> list[Path]:
    """Create a starter project at ``target_dir``. Returns the list of
    files written. Raises :class:`FileExistsError` if files would be
    overwritten and ``force=False``."""
    target_dir.mkdir(parents=True, exist_ok=True)

    files = {
        "pipelines.py": _PIPELINES_PY,
        "connections.toml": _CONNECTIONS_TOML,
        "Dockerfile": _DOCKERFILE,
        "flow.service": _FLOW_SERVICE,
        ".gitignore": _GITIGNORE,
        "README.md": _README,
    }

    written: list[Path] = []
    for relpath, contents in files.items():
        out = target_dir / relpath
        if out.exists() and not force:
            raise FileExistsError(
                f"{out} already exists; pass --force to overwrite, or "
                f"choose a different target directory"
            )
        out.write_text(contents)
        written.append(out)
    return written
